### ISSUE TITLE
databox.me is no longer maintained

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-idp-list#3]
databox.me is no longer maintained, largely due to the fact that the databrowser requires a popup which is not part of the code in gold

also the privacy page gives a 404

databox.me/privacy.html

there may be further issues, and this can be a place holder for anyone that would like to support it, or understand the steps to make it work again

it is however in use, and has 1000s of accounts, so the suggestion would be to gently turn off registration for now, but keep functionality for those already using it

further steps

- change the text in the json to reflect the current state

**Comment by Mitzi-Laszlo** [comment]
Hi Melvin, Thank you for this issue. I'm trying to concentrate all the Solid listings in one place (solidproject.org/use-solid) and currectly there is an issue open for experimental servers on https://github.com/solid/solid.github.io/issues/211 to be added to the 'for developers' tab on solidproject.org. I've made sure to link to this issue there too.
