### ISSUE TITLE
add solid.community to the services list

### ISSUE THREAD

**Issue by melvincarvalho** [solid/solid-idp-list#5]
add solid.community to the services list

consider what text we would like in the json too

**Comment by Mitzi-Laszlo** [comment]
Hi Melvin, Thank you for this issue. I'm trying to concentrate all the Solid listings in one place (solidproject.org/use-solid) and currently there is an issue open for experimental servers on https://github.com/solid/solid.github.io/issues/211 to be added to the 'for developers' tab on solidproject.org. I've made sure to link to this issue there too.
